### ISSUE TITLE
ERROR[12-21|10:59:42] No masternode found. Stopping node 

### ISSUE THREAD

**Issue by Dkdaniz** [XinFinOrg/XDPoSChain#116]
Hello guys,

I'm try use this bash https://github.com/XinFinOrg/Local_DPoS_Setup/blob/master/run.shhttps://github.com/XinFinOrg/Local_DPoS_Setup/blob/master/run.sh for run a local network, but I receive the error:

https://github.com/XinFinOrg/Local_DPoS_Setup/blob/master/run.sh

Any can help me?

❯ INFO [12-21|10:59:40] Block synchronisation started 
INFO [12-21|10:59:41] Imported new chain segment               blocks=15 txs=0 mgas=0.000 elapsed=5.474ms mgasps=0.000 number=15 hash=b1cf94…1e9922 cache=0.00B
INFO [12-21|10:59:41] Imported new chain segment               blocks=15 txs=3 mgas=0.263 elapsed=5.767ms mgasps=45.546 number=30 hash=09e7a2…e61460 cache=4.32kB
INFO [12-21|10:59:41] Imported new chain segment               blocks=31 txs=7 mgas=0.633 elapsed=10.187ms mgasps=62.128 number=61 hash=5e1163…81c154 cache=17.19kB
INFO [12-21|10:59:41] Imported new chain segment               blocks=134 txs=26 mgas=2.256 elapsed=36.178ms mgasps=62.361 number=195 hash=121659…53887c cache=60.58kB
INFO [12-21|10:59:42] Imported new chain segment               blocks=255 txs=51 mgas=4.468 elapsed=77.520ms mgasps=57.631 number=450 hash=aba0aa…c58cfe cache=103.57kB
INFO [12-21|10:59:42] It's time to update new set of masternodes for the next epoch... 
ERROR[12-21|10:59:42] No masternode found. Stopping node 

SO: MacOs Big Sur 11.1

**Comment by RushabhParmar12** [comment]
You need to define 3 nodes first in genesis block and it will work perfectly

**Comment by AnilChinchawale** [comment]
Hello @Dkdaniz ,

Kindly checkout and use the stable version of the codebase as below.
Commit :- d3963c8
Release :- https://github.com/XinFinOrg/XDPoSChain/releases/tag/v1.0.1

**Comment by Dkdaniz** [comment]
> Hello @Dkdaniz ,
> 
> Kindly checkout and use the stable version of the codebase as below.
> Commit :- [d3963c8](https://github.com/XinFinOrg/XDPoSChain/commit/d3963c816b5b1655b5a608e1d81329b4716c41aa)
> Release :- https://github.com/XinFinOrg/XDPoSChain/releases/tag/v1.0.1

Thanks for Support.

Was this code that I'm using. 

https://github.com/XinFinOrg/XDPoSChain/releases/tag/v1.0.1 + https://github.com/XinFinOrg/Local_DPoS_Setup/blob/master/run.sh

but don't start a consensus with masternode

I have a question. For I run a local network need only two projects correct?

**Comment by AnilChinchawale** [comment]
Yes using the above project you will able to run the private network, I would recommend you to generate a new genesis file using puppeth.

Feel free to join Technical Community Support at:

Telegram Community: https://t.me/XinFinDevelopers
Slack Community: https://xinfin-public.slack.com/messages/CELR2M831/
Slack Invitation Link: https://launchpass.com/xinfin-public
Technical help Resource: http://howto.xinfin.org/****

**Comment by Dkdaniz** [comment]
Thanks <3
