### ISSUE TITLE
how to build it 

### ISSUE THREAD

**Issue by wodingdong** [XinFinOrg/XDPoSChain#130]
I download this rep, and
I go to [ethereum/go-ethereum ](https://github.com/ethereum/go-ethereum) ,type
make geth
or
make all 
or 
make XDC
it does't build and not work

> root@root:/xdc/XDPoSChain# make XDC
> go: cannot find main module, but found vendor/vendor.json in /var/node/xdc/XDPoSChain
>         to create a module there, run:
>         go mod init
> build/env.sh go run build/ci.go install ./cmd/XDC
> build/ci.go:50:2: no required module provides package github.com/ethereum/go-ethereum/internal/build: go.mod file not found in current directory or any parent directory; see 'go help modules'
> Makefile:14: recipe for target 'XDC' failed
> make: *** [XDC] Error 1

how to build it?

**Comment by AnilChinchawale** [comment]
Hello,

Kindly use go v1.14 to build latest version of XDC.
