### ISSUE TITLE
Panic: interface conversion: interface {} is nil, not *types.Block at Block number 39058650 

### ISSUE THREAD

**Issue by RushabhParmar12** [XinFinOrg/XDPoSChain#150]
INFO [12-18|01:32:43] Initialising Ethereum protocol           versions="[63 62]" network=50
WARN [12-18|01:32:43] Head block missing, resetting chain      hash=f31614…9f2472
WARN [12-18|01:32:43] Rewinding blockchain                     target=0
panic: interface conversion: interface {} is nil, not *types.Block
goroutine 1 [running]:
github.com/XinFinOrg/XDPoSChain/core.(*BlockChain).CurrentBlock(...)
        /root/XinFin/XDPoSChain/core/blockchain.go:461
github.com/XinFinOrg/XDPoSChain/core.(*BlockChain).SetHead(0xc0057d6000, 0x0, 0x0, 0x0)
        /root/XinFin/XDPoSChain/core/blockchain.go:402 +0xc5b
github.com/XinFinOrg/XDPoSChain/core.(*BlockChain).ResetWithGenesisBlock(0xc0057d6000, 0xc000178ea0, 0x0, 0x0)
        /root/XinFin/XDPoSChain/core/blockchain.go:563 +0x64
github.com/XinFinOrg/XDPoSChain/core.(*BlockChain).Reset(0xc0057d6000, 0x1320a1a, 0x23)
        /root/XinFin/XDPoSChain/core/blockchain.go:556 +0x37
github.com/XinFinOrg/XDPoSChain/core.(*BlockChain).loadLastState(0xc0057d6000, 0x0, 0xc000178ea0)
        /root/XinFin/XDPoSChain/core/blockchain.go:291 +0x1a28
github.com/XinFinOrg/XDPoSChain/core.NewBlockChain(0x16e8580, 0xc005795640, 0xc0001aa540, 0xc00020aa00, 0x16e25a0, 0xc000213d10, 0x0, 0x0, 0x0, 0x0, ...)
        /root/XinFin/XDPoSChain/core/blockchain.go:235 +0x770
github.com/XinFinOrg/XDPoSChain/core.NewBlockChainEx(0x16e8580, 0xc005795640, 0x7fe88014a3f8, 0xc0001827e0, 0xc0001aa540, 0xc00020aa00, 0x16e25a0, 0xc000213d10, 0x0, 0x0, ...)
        /root/XinFin/XDPoSChain/core/blockchain.go:258 +0xbc
github.com/XinFinOrg/XDPoSChain/eth.New(0xc000126be0, 0xc0000fe000, 0xc0000a3100, 0xc00009e180, 0x0, 0xffffffffffffffff,
0x0)
        /root/XinFin/XDPoSChain/eth/backend.go:176 +0x809
github.com/XinFinOrg/XDPoSChain/cmd/utils.RegisterEthService.func2(0xc000126be0, 0xc0001a4150, 0xc0005fac38, 0xc0000e43f8, 0x0)
        /root/XinFin/XDPoSChain/cmd/utils/utils.go:27 +0xce
github.com/XinFinOrg/XDPoSChain/node.(*Node).Start(0xc00023d900, 0x0, 0x0)
        /root/XinFin/XDPoSChain/node/node.go:183 +0x3f9
github.com/XinFinOrg/XDPoSChain/cmd/utils.StartNode(0xc00023d900)
        /root/XinFin/XDPoSChain/cmd/utils/cmd.go:66 +0x2f
main.startNode(0xc00017e9a0, 0xc00023d900, 0x0, 0x32, 0x0, 0x0, 0x0, 0x64, 0x0, 0x200, ...)
        /root/XinFin/XDPoSChain/cmd/XDC/main.go:228 +0x89
main.XDC(0xc00017e9a0, 0xe, 0x1908b100)
        /root/XinFin/XDPoSChain/cmd/XDC/main.go:218 +0xf0
gopkg.in/urfave/cli%2ev1.HandleAction(0x1114e20, 0x1490e60, 0xc00017e9a0, 0xc00008a6c0, 0x0)
        /root/go/pkg/mod/gopkg.in/urfave/cli.v1@v1.20.0/app.go:490 +0xc8
gopkg.in/urfave/cli%2ev1.(*App).Run(0xc00011e1a0, 0xc000136000, 0x29, 0x2c, 0x0, 0x0)
        /root/go/pkg/mod/gopkg.in/urfave/cli.v1@v1.20.0/app.go:264 +0x5dd
main.main()
        /root/XinFin/XDPoSChain/cmd/XDC/main.go:207 +0x55

**Comment by wjrjerome** [comment]
FYI, this PR should fixed the issue: https://github.com/XinFinOrg/XDPoSChain/pull/153

**Comment by AnilChinchawale** [comment]
Fixed in v1.4.4, hence closing this issue.
