### ISSUE TITLE
Bug Report

### ISSUE THREAD

**Issue by mayong82** [XinFinOrg/XDPoSChain#152]
WARN [12-20|15:39:40] Synchronisation failed, dropping peer    peer=0eeb68a94b67445b err="retrieved hash chain is invalid"
WARN [12-20|15:44:38] Synchronisation failed, dropping peer    peer=1829d1df725df0c6 err="retrieved hash chain is invalid"
WARN [12-20|15:46:47] Synchronisation failed, dropping peer    peer=d8c5c907f9d70a59 err="retrieved hash chain is invalid"
WARN [12-20|15:46:54] Synchronisation failed, retrying         err="receipt download canceled (requested)"
WARN [12-20|15:47:08] Synchronisation failed, retrying         err="block body download canceled (requested)"
WARN [12-20|15:48:53] Synchronisation failed, dropping peer    peer=1f75a66764828c34 err="retrieved hash chain is invalid"
WARN [12-20|15:50:41] Synchronisation failed, dropping peer    peer=1010c1a9595ede64 err="action from bad peer ignored"
WARN [12-20|15:50:54] Failed to decode stats server message    err=EOF
WARN [12-20|15:51:06] Full stats report failed                 err="write tcp 172.19.0.2:38522->66.94.120.128:3000: use of closed network connection"
WARN [12-20|15:51:21] Synchronisation failed, dropping peer    peer=d87686f9f777636c err="retrieved hash chain is invalid"
You've encountered a sought after, hard to reproduce bug. Please report this to the developers <3 https://github.com/XinFinOrg/XDPoSChain/issues
index allocation went beyond available resultCache space
/work/xdcchain/eth/downloader/queue.go:510
goroutine 3376124 [running]:
runtime/debug.Stack(0x2b, 0x0, 0x0)
        /usr/local/go/src/runtime/debug/stack.go:24 +0x9d
runtime/debug.PrintStack()
        /usr/local/go/src/runtime/debug/stack.go:16 +0x22
github.com/XinFinOrg/XDPoSChain/common.Report(0xc02e93fa28, 0x1, 0x1)
        /work/xdcchain/common/debug.go:35 +0x1a5
github.com/XinFinOrg/XDPoSChain/eth/downloader.(*queue).reserveHeaders(0xc0051a6b00, 0xc00d4df3b0, 0x43, 0xc00fe6d920, 0xc0054613d8, 0xc00fe6d950, 0xc00fe6d980, 0x148ba80, 0x8000102, 0x0, ...)
        /work/xdcchain/eth/downloader/queue.go:510 +0x6cb
github.com/XinFinOrg/XDPoSChain/eth/downloader.(*queue).ReserveBodies(0xc0051a6b00, 0xc00d4df3b0, 0x43, 0x0, 0xc00d4df300, 0x0, 0x0)
        /work/xdcchain/eth/downloader/queue.go:462 +0xeb
github.com/XinFinOrg/XDPoSChain/eth/downloader.(*Downloader).fetchParts(0xc000552d80, 0x16acdc0, 0xc00016be30, 0xc005123c20, 0xc02e93fe90, 0xc00546cd20, 0xc02e93fe80, 0xc02e93fef0, 0xc02e93fee0, 0xc02e93fed0, ...)
        /work/xdcchain/eth/downloader/downloader.go:1116 +0x866
github.com/XinFinOrg/XDPoSChain/eth/downloader.(*Downloader).fetchBodies(0xc000552d80, 0x1d40387, 0x16acdc0, 0xc0320df600)
        /work/xdcchain/eth/downloader/downloader.go:937 +0x307
github.com/XinFinOrg/XDPoSChain/eth/downloader.(*Downloader).syncWithPeer.func4(0xa9b4a491b643786c, 0xe0a14f4942ef25da)
        /work/xdcchain/eth/downloader/downloader.go:466 +0x36
github.com/XinFinOrg/XDPoSChain/eth/downloader.(*Downloader).spawnSync.func1(0xc02eca6600, 0xc05640ca20, 0xc051cccda0)
        /work/xdcchain/eth/downloader/downloader.go:486 +0x53
created by github.com/XinFinOrg/XDPoSChain/eth/downloader.(*Downloader).spawnSync
        /work/xdcchain/eth/downloader/downloader.go:486 +0xc3
#### BUG! PLEASE REPORT ####
WARN [12-20|15:56:47] Synchronisation failed, dropping peer    peer=0eeb68a94b67445b err="retrieved hash chain is invalid"
WARN [12-20|15:56:53] Synchronisation failed, dropping peer    peer=35b51ac688cf4102 err="action from bad peer ignored"
WARN [12-20|16:01:03] Failed to decode stats server message    err=EOF

**Comment by AnilChinchawale** [comment]
Thank you for reporting, We have fixed this issue in the latest release v1.4.4.
