### ISSUE TITLE
can not deploy upgradeable contracts neither on apothem nor xinfin

### ISSUE THREAD

**Issue by rds0751** [XinFinOrg/XDPoSChain#160]
deploying simple upgradeable contract (Box.sol) of openzeppelin using hardhat

apothem
network id 51
node https://rpc.apothem.network

error
nonce already used
Error: nonce has already been used (error={"name":"ProviderError","code":-32000,"_isProviderError":true}, method="sendTransaction", transaction=undefined, code=NONCE_EXPIRED, version=providers/5.5.0)

tried many different contract even the basic upgradeable ones
example 
**pragma solidity ^0.6.0;

import "@openzeppelin/contracts-upgradeable/proxy/utils/Initializable.sol";

contract BaseContract is Initializable {
    uint256 public y;

    function initialize() public initializer {
        y = 42;
    }
}

contract MyContract is BaseContract {
    uint256 public x;

    function initialize(uint256 _x) public initializer {
        BaseContract.initialize(); // Do not forget this call!
        x = _x;
    }
}**

**Comment by AnilChinchawale** [comment]
Hello @rds0751 ,

Kindly use the remix which supports the latest version of solidity contracts.

https://remix.xinfin.network/
