### ISSUE TITLE
eth.blockNumber returning 8 hours old block

### ISSUE THREAD

**Issue by rds0751** [XinFinOrg/XDPoSChain#161]
![photo1649073646](https://user-images.githubusercontent.com/22606028/161540082-578a5b21-14b0-4b48-9aeb-5c044066fe76.jpeg)
all systems all instances of apothem network

**Comment by AnilChinchawale** [comment]
Hello, @rds0751 Thank you for reporting an issue, Kindly note issue has already been fixed.
