### ISSUE TITLE
Duplicated transactions

### ISSUE THREAD

**Issue by fishermanymc** [XinFinOrg/XDPoSChain#163]
It was discovered that there are duplicated transactiosn in XDC chain. For example: querying transaction with hash `0x2bc03e593e1e1ca3334754c4c6d9b0087511a3ceb79fd56c11d4a6d3d7ab8d36` using different methods yield different block information.

Method-1:

curl --location --request POST 'https://rpc.xinfin.network/'
--header 'Content-Type: application/json'
--data-raw '{
"jsonrpc":"2.0",
"id":100000,
"method":"eth_getTransactionReceipt",
"params":["0x2bc03e593e1e1ca3334754c4c6d9b0087511a3ceb79fd56c11d4a6d3d7ab8d36"]
}'

Return:

{
"jsonrpc": "2.0",
"id": 100000,
"result": {
"blockHash": "0x990a98f1a721dcb5af54a1a8312ff19942f2afb5b8d72baa889e879e531d27f8",
"blockNumber": "0x2801a94",
"contractAddress": null,
"cumulativeGasUsed": "0x0",
"from": "xdcb1efd51de35f2966c770cd35b953f4fdade3c3e8",
"gasUsed": "0x0",
"logs": [
{
"address": "xdc0000000000000000000000000000000000000092",
"topics": [],
"data": "0x",
"blockNumber": "0x2801a94",
"transactionHash": "0x2bc03e593e1e1ca3334754c4c6d9b0087511a3ceb79fd56c11d4a6d3d7ab8d36",
"transactionIndex": "0x0",
"blockHash": "0x02a2ab44ac0962f4c2e3ec55b072e49dd819307d964ad46e1bce01f2652f3456",
"logIndex": "0x0",
"removed": false
}
],
"logsBloom": "0x01000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000800000000000000000000000000000000000000004000000000000000000000000000000000000000000000000000000000000000",
"status": "0x1",
"to": "xdc0000000000000000000000000000000000000092",
"transactionHash": "0x2bc03e593e1e1ca3334754c4c6d9b0087511a3ceb79fd56c11d4a6d3d7ab8d36",
"transactionIndex": "0x0"
}
}

Method-2:

curl --location --request POST 'https://rpc.xinfin.network/'
--header 'Content-Type: application/json'
--data-raw '{"jsonrpc":"2.0","method":"eth_getBlockByNumber","params":["0x2801953",true],"id":1}'

Return:

{
"jsonrpc": "2.0",
"id": 1,
"result": {
"difficulty": "0x6b",
"extraData": "0xd8830104048358444389676f312e31342e3135856c696e757800000000000000ac45a43a36982d37bd9939c745e565d708e31845153bb250cbea7ec2c7be2b5459d51b5846ce24e989d7e5876d8583f92be45de906e10269552e045d12fd836000",
"gasLimit": "0x1908b100",
"gasUsed": "0x0",
"hash": "0x81c9d89e7b4985970b6a3e9a19a73f34a1c7203b85ec9beebd2927c00c255f19",
"logsBloom": "0x01000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000800000000000000000000000000000000000000004000000000000000000000000000000000000000000000000000000000000000",
"miner": "xdc0000000000000000000000000000000000000000",
"mixHash": "0x0000000000000000000000000000000000000000000000000000000000000000",
"nonce": "0x0000000000000000",
"number": "0x2801953",
"parentHash": "0x500d1d5c17ad591dc26b18c22104703ad3ec1efff745ad393f514ff2fb0e3a69",
"penalties": "0x",
"receiptsRoot": "0xbcd2a51669cdca54e5f28517bcd09ca95007951a7d7ec181cb3f361f783cde4a",
"sha3Uncles": "0x1dcc4de8dec75d7aab85b567b6ccd41ad312451b948a7413f0a142fd40d49347",
"size": "0x351",
"stateRoot": "0x547abeb5ae5052418f97701f19ebcc49c1f4b39a00d61f8c0828862b032b32d2",
"timestamp": "0x621f13ef",
"totalDifficulty": "0xcac55733",
"transactions": [
{
"blockHash": "0x81c9d89e7b4985970b6a3e9a19a73f34a1c7203b85ec9beebd2927c00c255f19",
"blockNumber": "0x2801953",
"from": "xdcb1efd51de35f2966c770cd35b953f4fdade3c3e8",
"gas": "0x2625a00",
"gasPrice": "0x0",
"hash": "0x2bc03e593e1e1ca3334754c4c6d9b0087511a3ceb79fd56c11d4a6d3d7ab8d36",
"input": "0x56e81f171bcc55a6ff8345e692c0f86e5b48e01b996cadc001622fb5e363b42156e81f171bcc55a6ff8345e692c0f86e5b48e01b996cadc001622fb5e363b421",
"nonce": "0x1c96c3",
"to": "xdc0000000000000000000000000000000000000092",
"transactionIndex": "0x0",
"value": "0x0",
"v": "0x88",
"r": "0xd7165e89be5330e2bec4778008bac8c77095927b19958f36aeebb471a11a03c7",
"s": "0x677c5212450594f1efe3adcea173713801b8f912aa7a3684982dddd2445f4ca2"
}
],
"transactionsRoot": "0x3e364c2e618bfb4d77c21218df6e1fdf298cefe22787d37940b19e4d2e80bd27",
"uncles": [],
"validator": "0xa5ded21b3ef468b4949b387c208ded2aac3d1e0b6a7b375bca784f9f28e766743d337834a16b6f9e6dc0f4dd52bf9ace5839a2b7bf9c193c45f0832a611287be00",
"validators": "0x"
}
}

**Comment by fishermanymc** [comment]
It appears that these duplicated transactions are placeholder transactions for XDC lending/trading services.

Their `to` addresses are `xdc000....092` to `xdc000...094` as defined in:
https://github.com/XinFinOrg/XDPoSChain/blob/dev-upgrade/common/types.go#L39-L41

And such transactions are treated as empty transactions during transaction execution:
https://github.com/XinFinOrg/XDPoSChain/blob/dev-upgrade/core/state_processor.go#L227

Thus, these transactions are harmless and can be ignored. They do not incur double-spending nor comproise the safty of XDC network.

**Comment by fishermanymc** [comment]
The following tool can find most of the duplicated transactions:
https://github.com/hash-laboratories-au/findDuplicates

**Comment by AnilChinchawale** [comment]
Thank you @fishermanymc.
