### ISSUE TITLE
Transactions are duplicated on testnet

### ISSUE THREAD

**Issue by APshenkin** [XinFinOrg/XDPoSChain#164]
In testnet two blocks contains same transaction 33946300 and 33946305 (tx hash 0x068b89421da8f91ce863d1661a2044730e57026a205305eac5031175fb0f5ba8). How can this even be?

```
[
    {
        "id": 1,
        "jsonrpc": "2.0",
        "method": "eth_getBlockByNumber",
        "params": ["0x205fabc", true]
    }
]
```

```
[
    {
        "id": 1,
        "jsonrpc": "2.0",
        "method": "eth_getBlockByNumber",
        "params": ["0x205fac1", true]
    }
]
```

**Comment by AnilChinchawale** [comment]
Hello @APshenkin ,

it has been well explained here, https://github.com/XinFinOrg/XDPoSChain/issues/163#issuecomment-1126853502
