### ISSUE TITLE
String reverts not working 

### ISSUE THREAD

**Issue by xcantera** [XinFinOrg/XDPoSChain#173]
We found a critical error on the network that makes a lot of code useless and can be a huge security problem.

The main network not working with "String reverts", for example when you have a revert on the smart contract. The network doesn't indicate what revert happened. (This is mandatory to fix it or most of the applications will not work if a revert happens)

This is a code example.

`function stake(uint256 tokenId, uint256 amountToStake) public nonReentrant {

    require(_exists(tokenId), "Invalid tokenId");       
    require(amountToStake <= _levels[_nfts[tokenId].level].dailymax, "Daily limit reached");
    require(_nfts[tokenId].laststake == 0 || _nfts[tokenId].laststake + 1 days < block.timestamp, "Daily limit reached");
    require(prnt.allowance(msg.sender, address(this)) >= amountToStake,"Insuficient Allowance");
    require(prnt.transferFrom(msg.sender,address(this),amountToStake),"transfer Failed");

    if (_nfts[tokenId].prnt==0){
        stakeValues.multiplierTotal +=  _nfts[tokenId].nftmultiplier;
    }else{
        stakeValues.totalweight -= _nfts[tokenId].weight;
    }

    stakeValues.totalPRNT += amountToStake;
    _nfts[tokenId].laststake = block.timestamp;
    _nfts[tokenId].stakeinlevel+=amountToStake;
    _nfts[tokenId].prnt+=amountToStake;
    if ( _nfts[tokenId].stakeinlevel >= _levels[_nfts[tokenId].level].tolevelup && _nfts[tokenId].level < 20){
        _nfts[tokenId].level += 1;
        _nfts[tokenId].stakeinlevel = 0;
        stakeValues.multiplierTotal +=  _levels[_nfts[tokenId].level].levelmultiplier;
        if (_nfts[tokenId].level > 1){
            stakeValues.multiplierTotal -=  _levels[_nfts[tokenId].level-1].levelmultiplier;
        }
    }
    weightCal(tokenId);
}`

We can see the next example with more details:

Im creating a jackpot smartcontract on the XDC network.

https://xdc.blocksscan.io/address/xdc4de3fb29288452474948d16296128048e5dbc700 - > Smartcontract on XDC

https://polygonscan.com/address/0x22568f35016a8bc0c61b21b5360f7340e46ead1e - > Smartcontract on Polygon

As you can see, you cant write the smartcontract with Blockscan(You cant write also with remix). Im doing the play buttons(functions) with requires.

```
function buttonClick() public payable {
        require(msg.value == 1 ether, "1 XDC required to bet!");
        if (activeGame)
            require(msg.sender != getLast(), "You are already winning!");
        currentTimeWin = now + 5 minutes;
        addressArr.push(msg.sender);
        activeGame = true;
    }
```

We know XDC network have a problem and require().... is not working in the network.

On polygon works perfect, on  xdc network is not working.

You can get the smartcontract code from the explorers, its verified!

**Comment by gzliudan** [comment]
@xcantera Do you mean the contract never reverts? Or the contract reverts but not report any reason string?

**Comment by xcantera** [comment]
@gzliudan if you check what I sent you will be able to see it.

First thing: The reverts dont send any error message.

Second thing: xdc4de3fb29288452474948d16296128048e5dbc700
This is an example in what the network is useless if you put reverts, this revert is used to create a button.(send a tx to the smartcontract). You will never be able to interact with this smartcontract until you fix this issue.

If you check it on polygon, its working perfect.

**Comment by gzliudan** [comment]
Would you please deploy the same contracts to test chain apothem ?

**Comment by xcantera** [comment]
I cant do it right now. You have the smartcontract codes (smartcontract are
verifie), copy the code and put it on the testnet

**Comment by gzliudan** [comment]
I deployed it on testnet just now: https://explorer.apothem.network/address/xdcb08ba7324663840621dd587e0a70a0eafff37e87#readContract

**Comment by xcantera** [comment]
I see it. As you can see, you cant write transactions.

**Comment by gzliudan** [comment]
The stake function you mentioned belongs to which contract? Would you please post the address and code?

**Comment by xcantera** [comment]
https://xdc.blocksscan.io/tokens/xdcf87f7dd4e47dd5bcac902c381ea0d2730db5c6ad#tokenTransfers

**Comment by gzliudan** [comment]
I checked the failed transations before 3-6 days ago, the fail reason messages are below:
```text
missing trie Node 7f2218d7f466aa5718812126428017753d2b68e24365197fce244a6eb7ebb3c1 (path )
missing trie Node f869c6e34823b8a14f8c33f0fdeb7fb2c42936fb6fe9fc9a2d036baee5a5a325 (path )
missing trie Node 5ba03ac903a1c8eb1d5d42c9ca55225708e18dd73ab2ab9615c76a40614cf9ea (path )
missing trie Node b4b069586810a654cb73a04bacfa5d4cf5c10d0c9fe53c2a70fc8cf6df5cc4a7 (path )
missing trie Node 3d9ffa7c545c145880d1e7ab5e9a7ad9fb39498d2ec7fc5513b8918949daf446 (path )
missing trie Node b7ee0ce15752c5385e3320a39da93eef8949ef11fe435fb5deac4d640f8366a1 (path )
missing trie Node 0417cc06299708cba750a6519f120b977ee586fcd2b6ff56a15ef8b7e8cebb13 (path )
missing trie Node 2d57b886fb1f2b65ad1219e4b9c5b219c8e3eac0fae392354db8cd70db7e0900 (path )
```
Maybe these error messages are caused by the bug of RPC node's. It seems the require commands in contract are executed right.

**Comment by xcantera** [comment]
Ok, please fix it.

**Comment by xcantera** [comment]
Check the other example also. You see that you cant interact with
smartcontract using xdc. But you can interact with the smartcontract using
polygon

**Comment by gzliudan** [comment]
We found 2 problems now:
1. Can't call write function on explorer web site
2. The failed transation report error message: `missing trie Node`

**Comment by xcantera** [comment]
Yes, exactly

**Comment by gzliudan** [comment]
I'll forword the information to XinFin blockchain development team.

**Comment by xcantera** [comment]
Awesome, thanks!

**Comment by gzliudan** [comment]
I found you are using ABDK Libraries. I opened a issue just now: https://github.com/abdk-consulting/abdk-libraries-solidity/issues/23.
> https://xdc.blocksscan.io/tokens/xdcf87f7dd4e47dd5bcac902c381ea0d2730db5c6ad#tokenTransfers

**Comment by BlocksScanIO** [comment]
Hello @xcantera & @gzliudan ,

You can find exact error reason on BlocksScan Explorer now , Kindly review and let us know.

Thank you

**Comment by gzliudan** [comment]
@BlocksScanIO Yes, the error message can be showed on blockscan exploer now. But the write functions can't be showed and called on blockscan exploer still now!

**Comment by BlocksScanIO** [comment]
Thank you for confirmation @gzliudan , Does write function for this contract work on remix ?

**Comment by gzliudan** [comment]
@BlocksScanIO I'm not using Remix. Please check:
https://xdc.blocksscan.io/address/xdc4de3fb29288452474948d16296128048e5dbc700 
https://explorer.apothem.network/address/xdcb08ba7324663840621dd587e0a70a0eafff37e87#readContract https://explorer.apothem.network/address/xdc7f3de014bfd22d06ec1852b0b179da1edda139d5#readContract

**Comment by xcantera** [comment]
Its not blocksscan issue. The write function have a requiere to abilitate
Write. Its network problem

**Comment by xcantera** [comment]
Cool! I see our smartcontract now show the error msg on Blocksccan. I will let you if it works with our interface

**Comment by gzliudan** [comment]
The page of `Write Contract` should show function buttonClick() and claimPrize() in the above contracts.

**Comment by xcantera** [comment]
Yes @gzliudan, it should  show function buttonClick() and claimPrize() in the above example contracts.

**Comment by xcantera** [comment]
Hey, guys @gzliudan the error is still the same.

Now you need to force a failing tx to see the error on Blocksscan.

We don't want to make people force the transaction when it's going to fail 100%.

I did test here: https://explorer.xinfin.network/address/xdc4b4336ec39321ab030459b51f256e2f00b960405#transactions
(If you force the tx you can see the error message from the revert)

As you can see the revert is not working if you don't force the tx.

**Comment by gzliudan** [comment]
Which transaction is not work as you expected?

**Comment by xcantera** [comment]
@gzliudan you need to force all the tx to get a revert. The revert should show the information before force the tx

**Comment by xcantera** [comment]
@gzliudan just try on your own. Use remix and use a smart contract with reverts. You will see that you don't see any information before forcing the tx.

**Comment by gzliudan** [comment]
Can you show me the code and how you call the function, such function name and parameters? Please tell me the actual result and the desired result that you want. Sorry, I don't konw what you mean when you say `forcing the tx`.

**Comment by xcantera** [comment]
Please check the VIDEO:

https://user-images.githubusercontent.com/34890623/190462777-bc0c8cda-36f1-499d-b26c-ffc9a8723c1c.mp4

**Comment by xcantera** [comment]
@gzliudan

**Comment by gzliudan** [comment]
I caught what you mean. If you execute a transaction which should be failed:
- If use xdc blockchain: MetaMask didn't warn, GAS is lost after you send the transtion.
- If use other blockchains.: MetaMask warn you that this transation will be reverted before send transaction, you can cancel the transaction if you see the waring, both of gas and time are saved.

**Comment by xcantera** [comment]
XDC blockchain didn't show the revert error before sending the tx with no
one wallet/interface(metamask, XDCpay, Remix...). There is no way to see
the error before sending the transaction.


As I explained on the video this is a big problem.

See the video complete please.

**Comment by gzliudan** [comment]
I did some tests today. When I send a fail transaction with remix, the below results occurred:
- Metamask does not alert user sometimes when use metamask + mumbai
- xdcpay alert when use xdcpay + apothem

I think both of metamask and xdcpay maybe alter or not alter user when send a transaction which will revert. And metamask alter me that a transaction will fail but it is executed successfully in fact last year. Both of them are not absolutely right at any time.

**Comment by xcantera** [comment]
Use remix. As I show you in the video, Remix show you the error before
sending the transaction.
We only care about before sending the transaction.

The network should tell you before sending the transaction if is going to
fail and the error message(revert). Like polygon do in the video.


In our interface mint.primenumbers.es we need this information. Right now,
we only getting the generic error what you see on the video. We need the
revert error before sending a tx to tell the user what is going on and why
he shouldn't do the tx.

**Comment by xcantera** [comment]
Again, you shouldn't send a tx to see the error message. You need to know
the error before sending the transaction.

**Comment by gzliudan** [comment]
Yes, I use remix to do tests. What I checked is metamask and xdcpay whether alert user before send transaction.

**Comment by xcantera** [comment]
Metamask and xdcpay only say the tx is going to fail. The reason???? You
need to send a fail tx to see it.

We dont care about metamask, XDCpay, Trezor, ledger, culopay....

We care about the network and the network is not telling you the revert
before you send the tx.

And the other networks tell you the revert before sending the tx.

**Comment by gzliudan** [comment]
We will investigate this problem in detail and work out a better solution. It seems that RPC nodes need to be optimized. I deployed a test contract to mumbai and apothem:

```solidity
// SPDX-License-Identifier: MIT
pragma solidity ^0.8.0;

contract TestRevert {
    uint256 public value = 0;

    function setValue(uint256 newValue) external {
        require(newValue < 10, "newValue >= 10");

        value = newValue;
    }
}
```

---

## test mumbai RPC

Request:
```shell
curl -X POST -H "Content-Type: application/json" https://rpc.ankr.com/polygon_mumbai -d '
{
  "jsonrpc":"2.0",
  "method":"eth_estimateGas",
  "params":[
    {
      "from":"0xD4CE02705041F04135f1949Bc835c1Fe0885513c",
      "to":"0x135cd8b7002c345b3da3e7712b77cae17d58b38e",
      "data": "0x55241077000000000000000000000000000000000000000000000000000000000000000a",
      "value":"0x0"
    }
  ],
  "id":1
}'
````

Response
```json
{
  "jsonrpc": "2.0",
  "id": 1,
  "error": {
    "code": 3,
    "message": "execution reverted: newValue >= 10",
    "data": "0x08c379a00000000000000000000000000000000000000000000000000000000000000020000000000000000000000000000000000000000000000000000000000000000e6e657756616c7565203e3d203130000000000000000000000000000000000000"
  }
}
```

---

## test apothem RPC

Request:
```shell
curl -X POST -H "Content-Type: application/json" https://rpc.apothem.network -d '
{
  "jsonrpc":"2.0",
  "method":"eth_estimateGas",
  "params":[
    {
      "from":"0xD4CE02705041F04135f1949Bc835c1Fe0885513c",
      "to":"0x41cfa4c7c764c39237a765788eb0596c4b7a05ba",
      "data": "0x55241077000000000000000000000000000000000000000000000000000000000000000a",
      "value":"0x0"
    }
  ],
  "id":1
}'
```

Response:
```json
{
  "jsonrpc": "2.0",
  "id": 1,
  "error": {
    "code": -32000,
    "message": "gas required exceeds allowance or always failing transaction"
  }
}
```

## conclusion

Ploygon give better reason. We need to optimize xinfin blockchain.

**Comment by xcantera** [comment]
All the tx with a revert. The network should send the error message before
force the tx

**Comment by AnilChinchawale** [comment]
Hi @xcantera ,

I would suggest you test Apothem RPC where we have applied the latest v1.4.6 to fix the reported issue.

{"jsonrpc":"2.0","id":1,"error":{"code":-32000,"message":"execution reverted: newValue \u003e= 10"}}

<img width="834" alt="Screenshot 2023-01-18 at 12 58 11 PM" src="https://user-images.githubusercontent.com/29918376/213109761-f0ce9f3b-880a-4df0-91f7-0bedc74f13a9.png">

**Comment by gzliudan** [comment]
@nitishpatel  Do you mean the following ?

|        Remix         |  Wallet  | Prompt revert |
| :------------------: | :------: | :-----------: |
|  remix.ethereum.org  | MetaMask |      Yes      |
| remix.xinfin.network | MetaMask |      Yes      |
|  remix.ethereum.org  |  XdcPay  |      No       |
| remix.xinfin.network |  XdcPay  |      No       |

**Comment by nitishpatel** [comment]
> @nitishpatel Do you mean the following result ?
> 
> Remix	Wallet	Prompt revert
> remix.ethereum.org	MetaMask	Yes
> remix.xinfin.network	MetaMask	Yes
> remix.ethereum.org	XdcPay	No
> remix.xinfin.network	XdcPay	No

@gzliudan Yes, Also It behaves similarly on dapp, XDCPay does return an error but with no string.
I wrote this a month back when I wasn't aware of this GitHub issue, it compares how each of the wallets is behaving differently for the same error, which is what my most concern is because XDCPay does returns an error but the reason is not part of it, so there is no way to find out why it's being reverted.

Context this error comes because I have a check before any transaction is done to see if it's likely to fail.
```
const result = await web3.eth.call(getCallOptionsFromCallObj(methodCallObj), blockNumber);
```
One can also check if its failing by just doing a `methodCallObj.estimateGas();`
https://www.xdc.dev/ncode/error-strings-support-in-xdc-4bec

**Comment by AnilChinchawale** [comment]
Hello, @nitishpatel Does [XDCPay 2.0 ](https://chrome.google.com/webstore/detail/xdcpay-20/iidmfamdbddcbjmemafekkohbnfiblhp)Work for you with remix.xinfin.network ?

**Comment by nitishpatel** [comment]
> Hello, @nitishpatel Does [XDCPay 2.0 ](https://chrome.google.com/webstore/detail/xdcpay-20/iidmfamdbddcbjmemafekkohbnfiblhp)Work for you with remix.xinfin.network ?
@AnilChinchawale Yes XDCPay 2.0 works and returns the error in a similar way as metamask does.

**Comment by wjrjerome** [comment]
Closing the issues as it was resolved
