### ISSUE TITLE
Support EIP-1898

### ISSUE THREAD

**Issue by gzliudan** [XinFinOrg/XDPoSChain#179]
XinFin blockchain does not support [EIP-1898](https://eips.ethereum.org/EIPS/eip-1898) now. Below methods are are affected:  
- eth_getBalance
- eth_getStorageAt
- eth_getTransactionCount
- eth_getCode
- eth_call

Here is a test case, request:
```shell
curl -X POST https://arpc.apothem.network/ -H "Content-Type: application/json" -d '
{
    "id": 348,
    "jsonrpc": "2.0",
    "method": "eth_call",
    "params": [
        {
            "data": "0x06fdde03",
            "gas": "0x2faf080",
            "to": "0x53350795c11cee781a7e174479778f848d76ab2a"
        },
        {
            "blockHash": "0xe8ec0bfc021f839fd0a69ae89689e309632af2cc434e8a096732068f0736864b"
        }
    ]
}'
```

And the response is:
```json
{
  "jsonrpc": "2.0",
  "id": 348,
  "error": {
    "code": -32602,
    "message": "invalid argument 1: hex string without 0x prefix"
  }
}
```

**Comment by Tpada13** [comment]
@gzliudan - XDC Network has recently implemented XIPs and this is a perfect example of one that can be written / copied over from the EIP.  Please check https://www.xdc.community/pages/xips/ and learn how to contribute and use the template to generate the XIP.   I will be happy to support the process if you would like to champion it through.

**Comment by gzliudan** [comment]
https://github.com/XDC-Community/XIPs.github.io/pull/14

**Comment by gzliudan** [comment]
@Tpada13  https://github.com/XDC-Community/XIPs.github.io/pull/14

**Comment by gzliudan** [comment]
The [graph-node](https://github.com/graphprotocol/graph-node) has a flag `no_eip1898`.
