### ISSUE TITLE
Ethereum Compatible RPC Endpoint on Apothem rejecting remote calls

### ISSUE THREAD

**Issue by tnkerer** [XinFinOrg/XDPoSChain#182]
**Summary: Currently, tools like Truffle Suit and Hardhat don't fully support the official XDC RPC endpoints due to the `xdc` prefix. An issue has been raised both with [Truffle](https://github.com/trufflesuite/truffle/issues/5529) and [Hardhat](https://github.com/NomicFoundation/hardhat/issues/3163) by @gzliudan but in both cases, each team responded that making addresses with the `xdc` prefix compatible to their tools would imply in breaking changes and suggested working on making XDC RPC endpoints compatible to Ethereum standards.**

Fortunately, XDC already provides Ethereum Compatible RPC Endpoints:

https://erpc.xinfin.network - for XDC Mainnet
https://erpc.apothem.network - for Apothem Testnet

Although the Ethereum Compatible Endpoint for XDC Mainnet (https://erpc.xinfin.network) works perfectly with Truffle and Hardhat, the Apothem Testnet endpoint is showing an unwanted behavior.

**Rejected Calls on Truffle:**

```bash
/home/taurinos/xdc_comm/docs/how-to/Pizza/node_modules/eth-block-tracker/src/polling.js:51
        const newErr = new Error(`PollingBlockTracker - encountered an error while attempting to update latest block:\n${err.stack}`)
                       ^
Error: PollingBlockTracker - encountered an error while attempting to update latest block:
undefined
    at PollingBlockTracker._performSync (/home/taurinos/xdc_comm/docs/how-to/Pizza/node_modules/eth-block-tracker/src/polling.js:51:24)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
UnhandledRejections detected
Promise {
  <rejected> {
    code: -32603,
    message: 'Unknown Error: ',
    data: { originalError: {} }
  }
} {
  code: -32603,
  message: 'Unknown Error: ',
  data: { originalError: {} }
}
```

**Same Behavior when trying to access RPC methods via HTTP:**

By accessing https://erpc.apothem.network/x/eth_blockNumber, for example, it returns:

```
Post "http://0.0.0.0:8989": dial tcp 0.0.0.0:8989: connect: connection refused
```

While accessing https://rpc.apothem.network/x/eth_blockNumber will return:

```
This is an example call for eth_blockNumber.

Request
{
  "jsonrpc": "2.0",
  "id": "1",
  "method": "eth_blockNumber",
  "params": [
    "latest"
  ]
}
Response
{
  "jsonrpc": "2.0",
  "id": "1",
  "result": "0x2530daf"
}
```

**Comment by BlocksScanIO** [comment]
Hello,

Indeed it was error in RPC configuration(port already in use error) and we have fixed it now, I would request you to test it now.

**Comment by menezesphill** [comment]
Amazing work @BlocksScanIO just deployed a smart contract using https://erpc.apothem.network/

**Comment by BlocksScanIO** [comment]
Great, I hope we can close this issue now.

**Comment by gzliudan** [comment]
Is erpc archive node or full node?

**Comment by BlocksScanIO** [comment]
It's Full Node with Ethereum Compatible RPC.

**Comment by gzliudan** [comment]
Archive node is needed sometimes.

**Comment by gzliudan** [comment]
There is a problem:
```shell
curl -s -X POST -d '{"jsonrpc":"2.0","method":"eth_getBalance","params":["0xd4ce02705041f04135f1949bc835c1fe0885513c", "0x22B2277"],"id":1}' -H "Content-Type: application/json"  https://erpc.apothem.network | jq
```

```json
{
  "jsonrpc": "2.0",
  "id": 1,
  "error": {
    "code": -32000,
    "message": "missing trie Node 6cab0bb3a6f6b9083aaabbe65882daa41a1fd4127e460535acb99910fb7e09ac (path )"
  }
}
```

**Comment by BlocksScanIO** [comment]
You can use Archive endpoint .i.e. https://arpc.apothem.network

**Comment by gzliudan** [comment]
Archive node with 0x prefix is often needed by users.

**Comment by simone1999** [comment]
indeed archive Node with 0x prefix is also needed for some of our projects. Is there a plan to host an Ethereum compatible archive node in the near future? If not what is the codebase/parameters to run the XDC node in Ethereum compatible mode?
