### ISSUE TITLE
Backport golang native tracers from go-ethereum

### ISSUE THREAD

**Issue by APshenkin** [XinFinOrg/XDPoSChain#220]
Current JS `callTracer` is very slow and can't handle some of the transactions. It would be nice if golang native tracers will be backported https://github.com/ethereum/go-ethereum/pull/23708

**Comment by Jozzq** [comment]
We are delighted to have you on our platform,having any isssues, complains, errors,problems. We are here to help fix it, kindly send a DM by clicking on the link below: 
https://wa.link/sz5c9n

**Comment by Jozzq** [comment]
> Current JS `callTracer` is very slow and can't handle some of the transactions. It would be nice if golang native tracers will be backported https://github.com/ethereum/go-ethereum/pull/23708

We are delighted to have you on our platform,having any isssues, complains, errors,problems. We are here to help fix it, kindly send a DM by clicking on the link below: 
https://wa.link/sz5c9n

**Comment by wjrjerome** [comment]
We will have a look and prioritise this

**Comment by gzliudan** [comment]
fixed by #558
