### ISSUE TITLE
Send transactions stuck in pending pool on xinfin node

### ISSUE THREAD

**Issue by evgeny-lebedev-crypterium** [XinFinOrg/XDPoSChain#263]
We are experiencing an issue with sending transactions to the XinFin blockchain. We have two XinFin nodes installed on our own infrastructure: CRYPTERIUM_PROD_NODE and CRYPTERIUM_PREPROD_NODE.

For sending transactions on CRYPTERIUM_PREPROD_NODE, we use a script written in Kotlin:

```
val url = <url of local xinfin node>
val mainAddress = <our own address>
val toAddress = <destination address>
val amount = "0.01"

// get current nonce

val nonceRequest = GetTransactionCountRequest(mainAddress)

val currentNonce = client.post<GetTransactionCountResponse>(url) {
    body = nonceRequest

    headers {
        header(HttpHeaders.ContentType, "application/json")
    }
}.result.let { Integer.decode(it) }

val nextNonce = currentNonce + 1

val sendRequest = CreateTransactionRequest(
    params = CreateTransactionParams(
        from = mainAddress,
        to = addressTo,
        value = value.toHex(),
        nonce = "0x" + nextNonce.toHexString()
    )
)

val hash = client.post<CreateTransactionResponse>(url) {
    body = sendRequest

    headers {
        header(HttpHeaders.ContentType, "application/json")
    }
}.result

// dto classes

data class GetTransactionCountRequest(
    val address: String,
    val method: String = "eth_getTransactionCount"
) : JsonRpcRequest<List<String>>(listOf(address, "latest"))

data class GetTransactionCountResponse(
    val result: String
)

//

class CreateTransactionRequest(
    params: CreateTransactionParams,
    val method: String = "eth_sendTransaction"
) : JsonRpcRequest<List<CreateTransactionParams>>(listOf(params))

data class CreateTransactionParams(
    val from: String,
    val to: String,
    val value: String,
    val nonce: String
)

data class CreateTransactionResponse(
    val result: String
)

//

open class JsonRpcRequest<T>(
    val params: T
) {
    val jsonrpc: String = "2.0"
    val id: Long = currentTimeMillis()
}

```

On CRYPTERIUM_PROD_NODE, we send transactions in the same manner, but without an explicit nonce in the request.

Subsequently,

* request with the method eth_getTransactionByHash to our node returns a transaction without a blockNumber.
* request with the method eth_getTransactionReceipt to our node also returns an empty result.
* searching for a transaction by hash on https://xdc.blocksscan.io/ returns a 404 response.
* request with the method txpool_status to our node returns {"jsonrpc":"2.0","id":1,"result":{"pending":"0x4af","queued":"0x1"}}.

This issue is reproducible on both nodes, regardless of whether the nonce is set explicitly or implicitly in the request. It first arose a month or two ago, despite having worked well before then.

What could be the solution to this issue?

**Comment by gzliudan** [comment]
How can I reproduce this problem step by step from zero?

**Comment by evgeny-lebedev-crypterium** [comment]
We just ran into this issue and don't know how to reproduce it. And now we need some help to research it.

**Comment by gzliudan** [comment]
But you said: 

```text
This issue is reproducible on both nodes
```

If you tell me how to reproduce the problem, I will try my best to research this issue.

**Comment by evgeny-lebedev-crypterium** [comment]
No, I mean we've experienced this issue on both nodes, but we don't have steps to reproduce. Problems just appeared at some point

**Comment by gzliudan** [comment]
@evgeny-lebedev-crypterium What's current status of this problem ?

**Comment by evgeny-lebedev-crypterium** [comment]
We are trying to change RPC
Relates to Remix/Metamask - we don't understand how it coul help in this case

**Comment by gzliudan** [comment]
If there's no problem when use metamask to send transactions directly, then maybe the Kotlin script is the reason.

**Comment by evgeny-lebedev-crypterium** [comment]
Is it possible to send transactions via metamask directly to our nodes?

**Comment by gzliudan** [comment]
You can use MetaMask send XDC coins to other account, this is the function of your Kotlin script did.

**Comment by evgeny-lebedev-crypterium** [comment]
We have two XDC nodes installed on our infrastructure. Which nodes will be used by MetaMask when I send XDC coins to someone? Is it possible to specife Crypterium nodes?

**Comment by gzliudan** [comment]
You can use this RPC `https://erpc.xinfin.network/` in MetaMask for test first. If no problem, then you can switch to a customized local RPC in MetaMask for test.

**Comment by evgeny-lebedev-crypterium** [comment]
Ok, will try it too

**Comment by gzliudan** [comment]
How about your test results?

**Comment by evgeny-lebedev-crypterium** [comment]
For now we decide to use public nodes

**Comment by gzliudan** [comment]
Does your Kotlin script work fine with public nodes now? Which node are you using?

**Comment by evgeny-lebedev-crypterium** [comment]
We tried https://rpc.xinfin.network/
Getting information from blockchain works fine. But we have issue with sending transactions and deploying smart contracts - requests should be signed. At the moment we are working on signing proccess on our side

**Comment by gzliudan** [comment]
I suggest you use RPC node https://erpc.apothem.network/ which support 0x-prefix. How is your work progressing, such as signing ?

**Comment by evgeny-lebedev-crypterium** [comment]
Thanks
Node https://rpc.apothem.network/ we using on our dev instance
Signing process implemented successfully. We will move these changes to production environment very soon.

**Comment by wjrjerome** [comment]
hi @evgeny-lebedev-crypterium could you confirm if this has been resolved on your end after switching to a different rpc url?
