### ISSUE TITLE
Hardhat: Upgradeable Proxy support for XDC

### ISSUE THREAD

**Issue by LogeswaranA** [XinFinOrg/XDPoSChain#326]
Unable to setup upgradeable proxy contract using Hardhat features. Setup is working fine with other evm compatible blockchain.

Erroring out with "ProviderError: too many arguments, want at most 1"

<img width="563" alt="image" src="https://github.com/XinFinOrg/XDPoSChain/assets/28006225/258826b7-5b5a-476e-8318-c787e3bbe611">

please try this : [github.com/GoPlugin/hardhat-proxy](https://github.com/GoPlugin/hardhat-proxy)

please check the README

**Comment by gzliudan** [comment]
I have reproduced this problem. I'll debug it later.

**Comment by gzliudan** [comment]
Please try ethers v5, it seems that ethers v6 cause this problem.

**Comment by LogeswaranA** [comment]
I have tried ethers version 5.7.0, it gives this error message
<img width="1015" alt="image" src="https://github.com/XinFinOrg/XDPoSChain/assets/28006225/e3d02c24-d48c-4a33-8c16-713d45252509">

**Comment by gzliudan** [comment]
You can try my test repo: https://github.com/gzliudan/erc20-hardhat/tree/ethers-v5

```bash
git clone https://github.com/gzliudan/erc20-hardhat.git
cd erc20-hardhat
git checkout ethers-v5

yarn
yarn clean
yarn compile

cp .env.sample .env
# set DEPLOYER_PRIVATE_KEY in file .env
vi .env

yarn deploy-token-v1:apothem
```

Your new error seems caused by compatibility. Please update your repo https://github.com/GoPlugin/hardhat-proxy, then I can look into it.

**Comment by gzliudan** [comment]
Please refer to my PR: https://github.com/GoPlugin/hardhat-proxy/pull/1. 

Main changes:

**package.json**

```json
    "@openzeppelin/hardhat-upgrades": "^1.28.0",
    "ethers": "^5.7.2",
```

**scripts/deploy.js**

```js
  await v1contract.deployed();
  console.log("Contract deployed to:", await v1contract.address);
```

**Comment by LogeswaranA** [comment]
Working fine now, this issue can be closed.

**Comment by gzliudan** [comment]
This issue is fixed on testnet now. The patch will be applied on mainnet later.
