### ISSUE TITLE
Weird gas estimation error : Out of gas (supplied gas 21199

### ISSUE THREAD

**Issue by Ekzer** [XinFinOrg/XDPoSChain#340]
Hi team!
We actually face a weird error when we try to estimate gas with just some arbritrary payload. This error happens on any addresses (accounts and smart-contract)

`[{"method":"eth_estimateGas","params":[{"data":"0xd0e30db0","from":"xdc3cc939888848682e92fdcd95c7ab53dbf169d0e1","to":"xdc722ad2c5330f4cffdc3775aa4574ec3cc7cf80a7","value":"0x9184e72a000"}],"jsonrpc":"2.0","id":1}]: 200 OK - [{"jsonrpc":"2.0","id":1,"error":{"code":-32000,"message":"err: out of gas (supplied gas 21199)"}}]`

This was performed to testnet.

This request works on any other networks (ETH, OP, ARB...)

Would you be able to investigate please?

Thank you very much in advance

**Comment by gzliudan** [comment]
Could you please provide the contract source code?

**Comment by Ekzer** [comment]
Hi @gzliudan !
This is not a smart contract call here, just precise some input data like this transaction here https://goerli-optimism.etherscan.io/tx/0xb85f5b6692576c183052c476402926cd5fc769128b44cf4ff3e6afebd4c9927b
the goal is to estimate gas for a transaction above 21000 gasLimit

**Comment by gzliudan** [comment]
Yes, I known. But I need a contract to test your issue since my contract has no such problem.

**Comment by gzliudan** [comment]
Yes, I known what you mean. But I need a contract to test your issue since my contract has no such problem. Please tell me your solidity version also.

**Comment by gzliudan** [comment]
@Ekzer How about the status of this issue?

**Comment by gzliudan** [comment]
@Ekzer We upgrade the testnet yesterday. Now it support the latest hardhat and remix. Would you please test this issue on testnet again? Or give me the source code of a contract to test it for you ?

**Comment by gzliudan** [comment]
@Ekzer How is this problem?

**Comment by calmacfadden** [comment]
I have the same issue. 
It is not possible to transfer XDC to an EOA and include arbitrary data. The result is an out of gas error. 
For me, it works fine if the destination is a contract. 

`When i try and estimate gas for a simple value transfer with some data to an EOA then it errors. But if i estimateGas with data to a contract then it succeeds. Any reason why i cant estimate gas with data?

Request:
curl https://rpc.apothem.network/ \
-X POST \
-H "Content-Type: application/json" \
-d '{"jsonrpc":"2.0","id":0,"method":"eth_estimateGas","params":[{"from":"0xf366aa107A5Ed1d54AFDEA5506B3059Ce402Da28","to":"0x53381ac6FE72C3cf469891F46248dc3dc02E8EA3","gas":"0x0","gasPrice":"0x0","value":"","data":"0xabcd012345"},"latest"]}'

Error: 

{
  "id": 0,
  "jsonrpc": "2.0",
  "error": {
    "code": -32000,
    "message": "err: out of gas (supplied gas 21199)"
  }
}`

**Comment by gzliudan** [comment]
I will look into this problem.

> I have the same issue. It is not possible to estimate gas for a transfer of XDC to an EOA and include arbitrary data. The result is an out of gas error. For me, it works fine if the destination is a contract.
> 
> When i try and estimate gas for a simple value transfer with some data to an EOA then it errors. But if i estimateGas with data to a contract then it succeeds. Any reason why i cant estimate gas with data?
> 
> Request: curl https://rpc.apothem.network/ -X POST -H "Content-Type: application/json" -d '{"jsonrpc":"2.0","id":0,"method":"eth_estimateGas","params":[{"from":"0xf366aa107A5Ed1d54AFDEA5506B3059Ce402Da28","to":"0x53381ac6FE72C3cf469891F46248dc3dc02E8EA3","gas":"0x0","gasPrice":"0x0","value":"","data":"0xabcd012345"},"latest"]}'
> 
> Error:
> 
> { "id": 0, "jsonrpc": "2.0", "error": { "code": -32000, "message": "err: out of gas (supplied gas 21199)" } }`

**Comment by gzliudan** [comment]
The address `0x53381ac6FE72C3cf469891F46248dc3dc02E8EA3` is not a contract. Only the contract can execute codes. So, both of the responses from your test case and below test cases are all right.

---

test case without parameter `data` should return normal value:

**request**

```bash
curl https://earpc.apothem.network/ -X POST -H "Content-Type: application/json" -d '
{
  "jsonrpc": "2.0",
  "id": 0,
  "method": "eth_estimateGas",
  "params": [
    {
      "from": "0xf366aa107A5Ed1d54AFDEA5506B3059Ce402Da28",
      "to": "0x53381ac6FE72C3cf469891F46248dc3dc02E8EA3"
    },
    "latest"
  ]
}'
```

**response**

```json
{
  "jsonrpc": "2.0",
  "id": 0,
  "result": "0x5208"
}
```

---

test case with parameter `data` should return error:

**request**

```bash
curl https://earpc.apothem.network/ -X POST -H "Content-Type: application/json" -d '
{
  "jsonrpc": "2.0",
  "id": 0,
  "method": "eth_estimateGas",
  "params": [
    {
      "from": "0xf366aa107A5Ed1d54AFDEA5506B3059Ce402Da28",
      "to": "0x53381ac6FE72C3cf469891F46248dc3dc02E8EA3",
      "data": "0xabcd012345"
    },
    "latest"
  ]
}'
```

**response**

```json
{
  "jsonrpc": "2.0",
  "id": 0,
  "error": {
    "code": -32000,
    "message": "err: out of gas (supplied gas 21199)"
  }
}
```

**Comment by Ekzer** [comment]
Hi @gzliudan, much apologies for my very late answer... Completely missed it.
I confirm what @calmacfadden says. We can't send arbitrary data to any address.
Another test case on mainnet : 

`[
    {
        "method": "eth_estimateGas",
        "params": [
            {
                "data": "0x48656c6c6f20576f726c6421",
                "from": "xdcd77875df9c9de07a5a701f4431743e3a0e9fe03a",
                "to": "xdce99500ab4a413164da49af83b9824749059b46ce"
            }
        ],
        "jsonrpc": "2.0",
        "id": 1
    }
]`

data here is just "Hello World!" hexyfied.
On any other ETH like networks this works.

**Comment by gzliudan** [comment]
@Ekzer @calmacfadden  If we send data to EOA, but EOA can't execute the code since it has no associated code, then the method `eth_estimateGas` will return error. I think this is the correct way to handle this case although other chains do not return error. What's your opinion?

**Comment by Ekzer** [comment]
@gzliudan well on first hand I would agree with you. But on the other hand, some services listen to arbitrary datas sent between addresses, or even to yourself. Such as Ordinals. Ordinals only rely on arbitrary datas mostly sent to yourself to save even more gas.

**Comment by gzliudan** [comment]
Let me ask the team.

**Comment by gzliudan** [comment]
I will update the codes of method `eth_estimateGas` about 3 weeks later.

**Comment by calmacfadden** [comment]
Yes, sending data to a non contract address is just a way to attach some arbitrary data to the transaction. 
It might just be something as simple as "These funds are from JIM" or it could contain some data that an external service relies on. 

Other ETH implementations just accept this data and simply charge the corresponding gas for its transmission on the network.

**Comment by alexchiriac** [comment]
@gzliudan 
May I ask: why or how was this simple functionality removed in XDC?

Estimating fees for sending a message together with a transfer transaction seems like a common use case, and the base go-ethereum implementation allows it. Hyperledger Besu as well. And I've seen it work on other networks such as Avalanche and Polygon.

Just curious if there was a reason or just an oversight during other updates.

Thanks 🙏

**Comment by gzliudan** [comment]
The method `eth_estimateGas` was added into XDC chain last year. Some code is not very perfect.
