### ISSUE TITLE
New Mainnet node with BlockHash issue fixed Unstable, keeps crashing

### ISSUE THREAD

**Issue by lucksin3** [XinFinOrg/XDPoSChain#376]
Deployed a node on Mainet using Master branch from-

- https://github.com/XinFinOrg/XDPoSChain &

- https://github.com/gzliudan/Local_DPoS_Setup

The node runs well for about 22-24 hours and then it crashes. Below are some of the logs from the machine:

![BlockHash-log](https://github.com/XinFinOrg/XDPoSChain/assets/101580552/d1b085cf-a7ab-499d-99c2-d665dd547cd5)
![blockHash-log1](https://github.com/XinFinOrg/XDPoSChain/assets/101580552/d6157537-bd9e-437f-9f2a-cf715e0d4ae5)

**Comment by lucksin3** [comment]
Here's more from the syslog:

root@ip-172-31-3-68:/var/log# grep -r XDC *
grep: journal/147b4a4f7a5f457482cf22e0a25cad59/system@00060bd453d791ef-03d392db7d63032a.journal~: binary file matches
grep: journal/147b4a4f7a5f457482cf22e0a25cad59/system.journal: binary file matches
kern.log:Dec  3 14:02:22 ip-172-31-3-68 kernel: [118163.517831] [    865]     0   865  2780267  1929847 18018304        0             0 XDC
kern.log:Dec  3 14:02:22 ip-172-31-3-68 kernel: [118163.517836] oom-kill:constraint=CONSTRAINT_NONE,nodemask=(null),cpuset=ssh.service,mems_allowed=0,global_oom,task_memcg=/user.slice/user-1000.slice/session-1.scope,task=XDC,pid=865,uid=0
kern.log:Dec  3 14:02:22 ip-172-31-3-68 kernel: [118163.517871] Out of memory: Killed process 865 (XDC) total-vm:11121068kB, anon-rss:7717596kB, file-rss:1792kB, shmem-rss:0kB, UID:0 pgtables:17596kB oom_score_adj:0
kern.log:Dec  4 21:10:57 ip-172-31-3-68 kernel: [36543.107850] [    859]     0   859  2779578  1901688 17096704        0             0 XDC
kern.log:Dec  4 21:10:57 ip-172-31-3-68 kernel: [36543.107855] oom-kill:constraint=CONSTRAINT_NONE,nodemask=(null),cpuset=user.slice,mems_allowed=0,global_oom,task_memcg=/user.slice/user-1000.slice/session-1.scope,task=XDC,pid=859,uid=0
kern.log:Dec  4 21:10:57 ip-172-31-3-68 kernel: [36543.107885] Out of memory: Killed process 859 (XDC) total-vm:11118312kB, anon-rss:7604960kB, file-rss:1792kB, shmem-rss:0kB, UID:0 pgtables:16696kB oom_score_adj:0
kern.log:Dec  6 22:58:53 ip-172-31-3-68 kernel: [47110.993181] [    990]     0   990  2762711  1931579 17743872        0             0 XDC
kern.log:Dec  6 22:58:53 ip-172-31-3-68 kernel: [47110.993186] oom-kill:constraint=CONSTRAINT_NONE,nodemask=(null),cpuset=ssh.service,mems_allowed=0,global_oom,task_memcg=/user.slice/user-1000.slice/session-1.scope,task=XDC,pid=990,uid=0
kern.log:Dec  6 22:58:53 ip-172-31-3-68 kernel: [47110.993232] Out of memory: Killed process 990 (XDC) total-vm:11050844kB, anon-rss:7724524kB, file-rss:1792kB, shmem-rss:0kB, UID:0 pgtables:17328kB oom_score_adj:0
syslog:Dec  3 14:02:22 ip-172-31-3-68 kernel: [118163.517831] [    865]     0   865  2780267  1929847 18018304        0             0 XDC
syslog:Dec  3 14:02:22 ip-172-31-3-68 kernel: [118163.517836] oom-kill:constraint=CONSTRAINT_NONE,nodemask=(null),cpuset=ssh.service,mems_allowed=0,global_oom,task_memcg=/user.slice/user-1000.slice/session-1.scope,task=XDC,pid=865,uid=0
syslog:Dec  3 14:02:22 ip-172-31-3-68 kernel: [118163.517871] Out of memory: Killed process 865 (XDC) total-vm:11121068kB, anon-rss:7717596kB, file-rss:1792kB, shmem-rss:0kB, UID:0 pgtables:17596kB oom_score_adj:0
syslog:Dec  4 21:10:57 ip-172-31-3-68 kernel: [36543.107850] [    859]     0   859  2779578  1901688 17096704        0             0 XDC
syslog:Dec  4 21:10:57 ip-172-31-3-68 kernel: [36543.107855] oom-kill:constraint=CONSTRAINT_NONE,nodemask=(null),cpuset=user.slice,mems_allowed=0,global_oom,task_memcg=/user.slice/user-1000.slice/session-1.scope,task=XDC,pid=859,uid=0
syslog:Dec  4 21:10:57 ip-172-31-3-68 kernel: [36543.107885] Out of memory: Killed process 859 (XDC) total-vm:11118312kB, anon-rss:7604960kB, file-rss:1792kB, shmem-rss:0kB, UID:0 pgtables:16696kB oom_score_adj:0
syslog:Dec  6 22:58:53 ip-172-31-3-68 kernel: [47110.993181] [    990]     0   990  2762711  1931579 17743872        0             0 XDC
syslog:Dec  6 22:58:53 ip-172-31-3-68 kernel: [47110.993186] oom-kill:constraint=CONSTRAINT_NONE,nodemask=(null),cpuset=ssh.service,mems_allowed=0,global_oom,task_memcg=/user.slice/user-1000.slice/session-1.scope,task=XDC,pid=990,uid=0
syslog:Dec  6 22:58:53 ip-172-31-3-68 kernel: [47110.993232] Out of memory: Killed process 990 (XDC) total-vm:11050844kB, anon-rss:7724524kB, file-rss:1792kB, shmem-rss:0kB, UID:0 pgtables:17328kB oom_score_adj:0

Suddenly the process is killed for OOM. whereas most of the time the memory threshhold is between 2-4 GB.

The server has 8GB memory

**Comment by wjrjerome** [comment]
Quick question, does the server has any settings around max docker memory it can use on the host machine?

**Comment by gzliudan** [comment]
@lucksin3  Do you still face this problem now?
