### ISSUE TITLE
API changes in latest release?

### ISSUE THREAD

**Issue by antondalgren** [XinFinOrg/XDPoSChain#389]
Has there been a change to the API response format in the latest release? Using Ethers v6 to fetch a transaction using `getTransaction(hash)` does not work as the to/from field is `xdc` prefixed. Has that change been made recently?

**Comment by gzliudan** [comment]
Would you please give a test example?

**Comment by antondalgren** [comment]
It seems to be related to a missing usage of `—enable-0x-prefix` setting. 

Thanks
