### ISSUE TITLE
Support API debug_traceCall

### ISSUE THREAD

**Issue by gzliudan** [XinFinOrg/XDPoSChain#513]
`debug_traceCall` is an API method that allows you to perform a `eth_call` on top of a given block using the final state of the parent block. It is used to debug and inspect call traces of transactions at run-time by setting certain debugging flags for transactions executing at the same or prior state.

XDC blockchain does not support the debug API [debug_traceCall](https://geth.ethereum.org/docs/interacting-with-geth/rpc/ns-debug#debugtracecall) now.

**Comment by liam-lai** [comment]
Report by EIP-4337 patch

**Comment by wgr523** [comment]
Code in PR: https://github.com/XinFinOrg/XDPoSChain/pull/545
