### ISSUE TITLE
Downgrade log

### ISSUE THREAD

**Issue by s1na** [XinFinOrg/XDPoSChain#584]
When node is syncing the logs are filled with lines like this. It makes it very hard to actually read the logs. I suggest setting the log level to debug for this particular info.

```
INFO [07-09|05:56:09] Signer reward                            signer=xdc1088C53E04D139A20A2f8998C586d27139a89A9B sign=60 reward=48076923076923076920
```

Same with iterating all the masternodes in the logs. Seems a bit verbose to me.

**Comment by gzliudan** [comment]
agree
