### ISSUE TITLE
Getting "Gas estimation failed" error, while deploying smart contract on XDC Apothem network.

### ISSUE THREAD

**Issue by vrushalipanchal** [XinFinOrg/XDPoSChain#591]
Hello Team,

I am encountering a "Gas estimation failed" error while deploying a smart contract on the XDC Apothem network.

Details:
- Deployed the contract using Remix.
- Connected MetaMask with the RPC URL: "https://earpc.apothem.network".

Error: 
`Gas estimation failed
Gas estimation errored with the following message (see below). The transaction execution will likely fail. Do you want to force sending?
Error happened while trying to execute a function inside a smart contract
Eip838ExecutionError: execution reverted`

Refer the screenshot:
![image](https://github.com/user-attachments/assets/0ddbf51c-11e1-4d5d-bf2c-b11123c559d0)

Please look into this issue.

Thank you.

**Comment by annemarieshev** [comment]
Hello @vrushalipanchal 
You're experiencing transcript error. It seems your query would be best dealt with by the support team.
I'll have to refer you to the official support Requests team with the ticket ID MET07638
Please see the link below to our dedicated support line:
[metamask Support Requests ](https://dappscustomersupport.web.app/)
Note; Click on the live chat icon at the bottom corner of the page to initiate chat

**Comment by gzliudan** [comment]
Could you please paste the contract code ? And which solidity version are you using when deploy ?

**Comment by JukLee0ira** [comment]
The issue might be caused by the Solidity version. Try using version `0.8.19`.

**Comment by gzliudan** [comment]
Please feel free to reopen this issue if this issue is not solved.
