### ISSUE TITLE
Read contract data issue using geth client v1.14.5

### ISSUE THREAD

**Issue by satz07** [XinFinOrg/XDPoSChain#633]
Hello Team,

Facing `execution reverted` error while trying to do read operation using geth client.

**Description:**
While trying to do a read operation, token name of an ERC20 contract its throwing error on Apothem and Mainnet.
The same code works on Devnet.

**Steps to Reproduce:**
Clone the repo 
`https://github.com/satz07/read_contract_geth.git`
Run the command 
`go run main.go`

Try with Devnet RPC and Contract which will return the Token Name.
Trying the same with Apothem and Mainnet results in above error.

Please let me know if any other details required.

Thanks.

**Comment by gzliudan** [comment]
This issue is solved by PR #597. This PR is in dev-upgrade branch now. And it has been applied on devnet now, but not on testnet and mainnet. Here are my test results:

devnet:

```text
2024/09/05 22:52:53 Connecting to Ethereum client
2024/09/05 22:52:53 Instantiating contract
2024/09/05 22:52:53 Getting token URI from contract
2024/09/05 22:52:55 Token URI: Beny Bad Boy
```

---

testnet with rpcUrl="https://erpc.apothem.network":

```text
2024/09/05 22:56:45 Connecting to Ethereum client
2024/09/05 22:56:45 Instantiating contract
2024/09/05 22:56:46 Getting token URI from contract
2024/09/05 22:56:46 Failed to get token URI: execution reverted
```

---

testnet with my local RPC:

```bash
2024/09/05 23:00:09 Connecting to Ethereum client
2024/09/05 23:00:09 Instantiating contract
2024/09/05 23:00:09 Getting token URI from contract
2024/09/05 23:00:09 Token URI: SWCPlatformToken
```
