### ISSUE TITLE
index allocation went beyond available resultCache space index=8195 len.resultCache=8192 blockNum=80379140 resultOffset=80370945

### ISSUE THREAD

**Issue by fz22gq** [XinFinOrg/XDPoSChain#671]
You've encountered a sought after, hard to reproduce bug. Please report this to the developers <3 https://github.com/XinFinOrg/XDPoSChain/issues
index allocation went beyond available resultCache space
/builder/eth/downloader/queue.go:514
goroutine 57108 [running]:
runtime/debug.Stack()
        /usr/local/go/src/runtime/debug/stack.go:24 +0x5e
runtime/debug.PrintStack()
        /usr/local/go/src/runtime/debug/stack.go:16 +0x13
github.com/XinFinOrg/XDPoSChain/common.Report({0xc036607a08, 0x1, 0x1})
        /builder/common/debug.go:35 +0x12a
github.com/XinFinOrg/XDPoSChain/eth/downloader.(*queue).reserveHeaders(0xc00d9fa600, 0xc04193ea50, 0x80, 0xc036607ae0?, 0xc00d8fe8c8, 0x0?, 0xc036607af0?, 0x1463770)
        /builder/eth/downloader/queue.go:514 +0x736
github.com/XinFinOrg/XDPoSChain/eth/downloader.(*queue).ReserveBodies(0xd1d146?, 0xd34ba5?, 0xc036607b48?)
        /builder/eth/downloader/queue.go:465 +0xe5
github.com/XinFinOrg/XDPoSChain/eth/downloader.(*Downloader).fetchParts(0xc000602d00, {0x15d1580, 0x1d5c5c0}, 0xc00d7d7860, 0xc036607ea8, 0xc00d8d8c40, 0xc036607e98, 0xc036607f08, 0xc036607ef8, 0xc036607ee8, ...)
        /builder/eth/downloader/downloader.go:1121 +0xcbb
github.com/XinFinOrg/XDPoSChain/eth/downloader.(*Downloader).fetchBodies(0xc000602d00, 0x22b97093f4d08cfc?)
        /builder/eth/downloader/downloader.go:942 +0x29f
github.com/XinFinOrg/XDPoSChain/eth/downloader.(*Downloader).syncWithPeer.func4()
        /builder/eth/downloader/downloader.go:471 +0x1e
github.com/XinFinOrg/XDPoSChain/eth/downloader.(*Downloader).spawnSync.func1()
        /builder/eth/downloader/downloader.go:491 +0x5d
created by github.com/XinFinOrg/XDPoSChain/eth/downloader.(*Downloader).spawnSync in goroutine 56795
        /builder/eth/downloader/downloader.go:491 +0x7a
#### BUG! PLEASE REPORT ####

**Comment by gzliudan** [comment]
Need PR #563

**Comment by gzliudan** [comment]
v2.4.0 will include PR #563.
